apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
        httpMethod: GET
        tracesToLogs:
            datasourceUid: 'loki'
    version: 1
    
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    
    jsonData:
      derivedFields:
      - datasourceUid: tempo
        matcherRegex: \[.+,(.+?),
        name: TraceID
        url: $${__value.raw}
    version: 1


jsonData: